### ISSUE TITLE
Rounding issue in the merge positions preview

### ISSUE THREAD

**Issue by elena-zh** [gnosis/conditional-tokens-explorer#613] opened 2020-11-13 11:50 UTC
'Amount' field allows to enter up to 18 decimals while only 2 decimals are displayed in the merge positions preview (see the pic)
![rounding.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/41404bbd-aedd-42c6-86fb-8a7b971670a4)

**Expected Result**: the values should be consistent

**Comment by mariano-aguero** [comment] 2020-11-27 15:19
Mmmm I consider this isn't a bug, In fact, if we go with this we can cause some problems in the application, regarding some round issues.
If the user have an amount of 0.1691243 and because rounding, can enter an amount of 0.17 because the application will manage 2 decimals, this will cause an error. Also the user should be able to enter the amount of decimals that the user wants, not only 2. I think allowing the user to enter more than 2 decimals is better than not (is better to allow to restrict in this case), so I will close this issue, with a label `wontfix`. If someone comes up with a case that is really worth making this improvement, we can reopen it

**Closed by mariano-aguero** 2020-11-27 15:19 UTC
Labels: Low priority, bug

**Comment by elena-zh** [comment] 2020-11-27 15:23
@mariano-aguero , as another option we can change the preview section and show the amount = value in the amount field and not limit it to 2 decimals in the preview.

**Comment by mariano-aguero** [comment] 2020-11-27 15:45
> @mariano-aguero , as another option we can change the preview section and show the amount = value in the amount field and not limit it to 2 decimals in the preview.

Mmmm one case is to enter an amount of X, the user should enter the amount that she/he wants , without a restriction of decimals. The other case is `How we display the information to the user`, now we are using 2 decimals in all the cases, if we want to give more information to the user in this kind of case, maybe we can think in a better option (of course, taking every case in particular), for example, the balance of the wallet maybe we can add a tooltip (title) with the total amount without decimals restriction. Probably this is an enhancement an not a bug
