### ISSUE TITLE
[FE] Crash when splitting from a condition with many outcomes

### ISSUE THREAD

**Issue by gabitoesmiapodo** [gnosis/conditional-tokens-explorer#490] opened 2020-10-19 16:04 UTC
When splitting a position from a condition with many outcomes (for example 61 as with condition `0xe4fc24ff668887733b96bd928ccaf715e2c7f9331b32352ece3178820459cfa7`) the app will crash with an error like this one:

![Screen Shot 2020-10-19 at 12.53.48.png](https://images.zenhubusercontent.com/5dd4002e59c2320001aa6485/01703a7a-89c4-481e-ba5e-be663ee556ef)

- Go to "Split Position" 
- Fill in "Condition ID" with `0xe4fc24ff668887733b96bd928ccaf715e2c7f9331b32352ece3178820459cfa7`  (or any other condition with a substantial amount of outcomes).
- Fill every other input.
- You can also edit the partition, but it's not necessary.
- Click split.

Tried this with (all have more than 31 outcomes): 

`0xe4fc24ff668887733b96bd928ccaf715e2c7f9331b32352ece3178820459cfa7` `0xf1c1075bc6e88dc4e848934e6f0148c9c40003c2ab63d634e5c76d46c5e07bf0`
`0xecab5c10f281a3299f17aab702c24543c6f9f2ada83922c5fe934d749a32d142`
`0xceb9e06e8fdb33faef4f65a1af5ef1e33bb24305eb84ade492bd78fa3c38ed7f`

From 31 outcomes and below it seems to work fine:

`0x63c36521ce93b8d1c1302168bcc4bdf06949bd93e2c1653780a7dc4d3a1aa9f2`

**Comment by hpmaxi** [comment] 2020-10-19 17:45
Seems like a duplicate of #261 .

**Comment by gabitoesmiapodo** [comment] 2020-10-19 18:30
@hpmaxi To avoid further problems you may want to update the title ("Split position with non-custom collateral fails") and description of that issue, because they don't seem related to this one at first glance.

**Comment by hpmaxi** [comment] 2020-10-19 18:59
@gabitoesmiapodo Done, I've updated the title, we could close both when the issue is solved.

**Comment by elena-zh** [comment] 2020-11-02 14:46
works fine. 
however, now the transaction fails when split a condition with more than 69 outcomes (#574)

**Closed** 2020-11-02 14:46 UTC
Labels: Medium priority, QA Passed, bug
