### ISSUE TITLE
No need to select and then confirm condition when splitting

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/conditional-tokens-explorer#542] opened 2020-10-28 20:44 UTC
When splitting a condition, you have to first select and then confirm a condition (and a position if splitting from a position).

Given that you can only select one condition (and position), there is no need for this to be a two step process.

![image](https://user-images.githubusercontent.com/8453294/97494476-bf1ccd00-193c-11eb-9e89-daa3ab6d5e7f.png)

**Comment by gabitoesmiapodo** [comment] 2020-11-18 19:40
Probably invalid after we merge https://github.com/gnosis/conditional-tokens-explorer/pull/597

(@elena-zh please check it)

**Comment by elena-zh** [comment] 2020-11-19 09:23
@gabitoesmiapodo , yes, the issue is not relevant in the new design of the Split position page as the select position/condition pop-ups are removed.
I'm closing the task.

**Closed** 2020-11-19 09:23 UTC
Labels: Low priority, enhancement, feature requested
