### ISSUE TITLE
Render question text, rather than ID, for Omen/Reality.eth conditions and positions

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/conditional-tokens-explorer#541] opened 2020-10-28 20:32 UTC
In the list views, we should render the question text (probably truncated), rather than the question ID, in the conditions and positions list views, along with the similar views in the split, merge, resolve, and redeem modals.

**Comment by elena-zh** [comment] 2020-10-29 11:15
Seems to be a duplicate of #539

**Comment by auryn-macmillan** [comment] 2020-10-29 13:33
Agreed, seems to be a duplicate.

**Closed** 2020-10-29 20:12 UTC
Labels: Medium priority, duplicate, enhancement, feature requested
